### ISSUE TITLE
Create zchunk metadata

### ISSUE THREAD

**Issue by mikhailnov** [OpenMandrivaSoftware/rosa-publish-worker#10]
Добавьте `--zck` к вызову createrepo_c , `--xz` можно убрать. Нужны метаданные в формате zchunk, чтобы при обновлении метаданных выкачивать не все метаданные, а только дельту изменений, сейчас же обновление метаданных идет настолько долго, что можно успеть выпить чай!

https://fedoraproject.org/wiki/Changes/Zchunk_Metadata

@fedya

**Comment by fedya** [comment]
fixed https://github.com/OpenMandrivaSoftware/docker-abf/commit/36748e293d445c7b7ead053beeea709ac3158da4
