### ISSUE TITLE
Same version build

### ISSUE THREAD

**Issue by aenikitin2048** [OpenMandrivaSoftware/rosa-publish-worker#2]
Building same version-release should not fail tests on server platfrms as we do not autoincrement release on build
https://abf.io/build_lists/2965405

**Comment by fedya** [comment]
Uncheck "extra tests" button

**Comment by aenikitin2048** [comment]
отмена галочки "Использовать дополнительные тесты" ни к чему не приводит
В билдлисте всё равно "Использовать дополнительные тесты | Да"
и тесты всё равно валятся
